language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - cp django_airavata/settings_local.py.sample django_airavata/settings_local.py
  - python manage.py migrate
  - python manage.py check
